# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7da603ecbf5433e9e8302086aa2a8967d42eccd233503ee1167679ecfb1a1af3c94578bfdccc101d03019e536436f6531083441a3a4e7a3f48f2350e87e628b

test:
  secret_key_base: 08f049af383f6982f7508257b739d9ddc3b72f896c0190d2a400e210a0044707b88ca4d705b643dfa6f89da65dbd1478fd5062f1e2d63050825ed1c7d492611c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
